# 端口
server:
  port: 8772
spring:
  application:
    name: eureka-client2
# Eureka配置
eureka:
  instance:
    # eureka服务端的实例名称
    hostname: client
  client:
     service-url:
      defaultZone: http://localhost:8761/eureka